### ISSUE TITLE
Flashing light on death or win

### ISSUE THREAD

**Issue by yujene** [jgordon510/quick_bloxorz#1]
The flash of light should probably be removed from the game for photosensitive players or viewers. Otherwise, there should be a warning displayed or there should be a setting to disable it.

**Comment by jgordon510** [comment]
I'm following the guidelines here: https://trace.umd.edu/peat/

Which state: 
In general, web or computer content will not provoke seizures if either of the following is true:
- **There are no more than three general flashes and no more than three red flashes within any one-second period,**

- The combined area of flashes occurring concurrently occupies no more than a total of one quarter of any 341 x 256 pixel rectangle anywhere on the displayed screen area when the content is viewed at 1024 by 768 pixels.

I have met the first requirement.  I only flash the screen once in any one-second period.

**Comment by yujene** [comment]
Good to hear that the current implementation meets the guidelines. However, I think it would still be beneficial to include an option to disable the flashes because multiple people have stated that it is quite jarring and difficult to view.

**Comment by jgordon510** [comment]
I desaturated them, which should make the flash less intense.  There needs to be a win/loss indication and a background color change is simple and doesn't require extra titling.
