### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by yujene** [jgordon510/quick_bloxorz#2]
The camera following the block can be visually jarring, so a stationary camera like the original game would be nice as a permanent change or a togglable option.

**Comment by jgordon510** [comment]
I might be able to add a stationary camera, but that would require detecting (or setting) the center point of the puzzles.  If so, I would make it a non-default toggleable option.

**Comment by jgordon510** [comment]
I've added an options menu and implemented a fixed camera position.
