### ISSUE TITLE
Timer for speedrunning

### ISSUE THREAD

**Issue by yujene** [jgordon510/quick_bloxorz#3]
A quality of life change for timing in speedruns would be to have a millisecond timer built into the game. The timer could track the total time with each stage recorded individually as well.

**Comment by jgordon510** [comment]
I thought about doing this, but I wasn't sure how the behavior should work.

If I restart a stage, should that restart the time for that stage, but not the whole game?

**Comment by yujene** [comment]
I think total timer should only get reset with "Start New Game", but I'm not certain about time for the stage.

For full category runs like 10, 20, 33 level, I think it would be nice to have the time between entering a stage and successfully reaching the next one since it would line up with the splits we'd be using.

Alternatively, there could be an individual level (IL) timer option that resets with the stage.
