### ISSUE TITLE
Swap issues

### ISSUE THREAD

**Issue by yujene** [jgordon510/quick_bloxorz#4]
The issues regarding swaps are shown in the videos below with input display.

Inputting directions while holding space seems to swap pieces. Swap should only occur on initial press of the spacebar.
https://user-images.githubusercontent.com/81407061/112687942-8d0d8980-8e4e-11eb-80dd-fc523e67b5fb.mp4
Stage: 8
Inputs: hold space, right, right, right, right, right, release space

The last right arrow direction input doesn't move the block. This is the shortest sequence of inputs I could do to reproduce it.
https://user-images.githubusercontent.com/81407061/112687948-8e3eb680-8e4e-11eb-99f8-6cd713248cf1.mp4
Stage: 8
Inputs: right, right, hold space, right, release space, hold space, right, release space

**Comment by jgordon510** [comment]
Should be all good on these.  Thanks for great steps to reproduce.
