### ISSUE TITLE
Stage 4

### ISSUE THREAD

**Issue by yujene** [jgordon510/quick_bloxorz#5]
The weak tiles at the top of the stage are 8 wide when it should be 7.
![quick](https://user-images.githubusercontent.com/81407061/112879191-d6e8b080-9096-11eb-8532-c347885f32c8.png)
![orig](https://user-images.githubusercontent.com/81407061/112879193-d819dd80-9096-11eb-9893-e1607047a808.png)

**Comment by jgordon510** [comment]
Good catch.  Fixed.
